server:
  port: 8080

#注册服务
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    prefer-ip-address: true

spring:
  profiles:
    active: dev

  application:
    name: vip-center

  cloud: #使用DiscoveryClient找到配置服务器
    config:
      discovery:
        # 使用eureka发现配置中心服务
        enabled: true
        # 配置中心服务名称/ID
        serviceId: config
      uri: http://127.0.0.1:11111 #配置服务
      label: master

#log配置
logging:
  config: classpath:logback.xml
  path: ${user.home}/logs/${spring.application.name}
  level:
    com.ibatis: DEBUG
    org.springframework.kafka: ERROR

#终端 配置
management:
  # 启用shutdown,优雅的关闭服务，默认是false
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        #暴露actuator中的某些接口， refresh 刷新config配置信息
        include: '*'

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  type-aliases-package: com.xxx.mall.mapper
#  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check



