server:
  port: 8080

# mysql and tk.mybatis
spring:
  application:
    name: vip-center
  datasource:
    url: jdbc:mysql://192.168.112.31:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: eCityArcTest
    password: rickControl@test
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.106.76
    database: 6
    port: 6379
    password: Hello1234

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  type-aliases-package: com.xxx.mall.mapper
#  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check


#注册服务 registry_center
eureka:
  client:
    service-url:
      defaultZone: http://172.20.51.215:8000/eureka/
  instance:
    prefer-ip-address: true

