server:
  port: 8082

#注册服务
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    prefer-ip-address: true

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

com:
  lhx:
    name: 李四

spring:
  application:
    name: route-center
  cloud: #使用DiscoveryClient找到配置服务器
    config:
      discovery:
        enabled: true
      uri: http://127.0.0.1:11111 #配置服务
