server:
  port: 8081

spring:
  application:
    name: order-center

#注册服务 registry_center
eureka:
  client:
    service-url:
      defaultZone: http://172.20.51.215:8000/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
