spring:
  application:
    name: register-center

server:
  port: 8000


eureka:
  instance:
    ip-address: 172.20.51.215 # 指定此实例的ip
    prefer-ip-address: true # 注册时使用ip而不是主机名
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://172.20.51.215:8000/eureka/




