spring:
  application:
    name: register-center

server:
  port: 10010


eureka:
  instance:
    ip-address: 10.100.120.44
    prefer-ip-address: true # 注册时使用ip而不是主机名
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    serviceUrl:
        defaultZone: http://10.100.120.45:10010/eureka/,http://10.100.120.40:10010/eureka/
    fetch-registry: true
    register-with-eureka: true




